const TYPE_COUNTRIES_DATA = "TYPE COUNTRIES DATA";
const TYPE_OPEN_MODAL = "TYPE OPEN MODAL";
const TYPE_MODAL_INFO = "TYPE MODAL INFO";
const TYPE_GET_SEARCH_VALUE = "TYPE GET SEARCH VALUE";
const TYPE_SORTING_COUNTRIES_DATA = "TYPE SORTING COUNTRIES DATA";


export {
  TYPE_COUNTRIES_DATA,
  TYPE_OPEN_MODAL,
  TYPE_MODAL_INFO,
  TYPE_GET_SEARCH_VALUE,
  TYPE_SORTING_COUNTRIES_DATA
}